### PR TITLE
fix: add support for entry chunks with no imports

### LINKED ISSUE #20: Entry chunks with no imports throw a runtime error (ReferenceError: __webpack_require__ is not defined)
Included my description of the issue and a fix in #19

### PR DESCRIPTION
**Pull request by markjm**
Entry chunks which do not import/require any other modules will not have __webpack_require__ defined, leading to a runtime failure. Lets protect against this by checking for the existance of __webpack_require__ before trying to use it. It is a very small amount of increased code, and may possibly be minified out (though I have not verified).

To validate that the described scenario is broken, try running the e2e test server with the included index-no-import.js. Also used this to validate my fix (no runtime error in webpack runtime).

I know it seems strange to want this retry plugin for chunks that dont have anything that would get value from it, but we have a multiple-entry-chunk project. While it is probably possible to use `chunks` (though an excludedChunks may fit a little better), I dont see any harm in providing this runtime safety check.

Closes #20

### CODE REVIEW

**Comment by markjm** [comment]
Hi @mattlewis92 - thanks for writing and maintaining this plugin!

I think this is a safe and valuable fix - interested to hear your thoughts!

File: src/index.js [hunk 1]
```diff
@@ -32,37 +32,39 @@ class RetryChunkLoadPlugin {
...
-            return result.catch(function(error){
-              var retries = countMap.has(chunkId) ? countMap.get(chunkId) : ${maxRetries};
-              if (retries < 1) {
-                var realSrc = oldGetScript(chunkId);
-                error.message = 'Loading chunk ' + chunkId + ' failed after ${maxRetries} retries.\\n(' + realSrc + ')';
-                error.request = realSrc;${
-                  this.options.lastResortScript
-                    ? this.options.lastResortScript
-                    : ''
+          if(typeof ${RuntimeGlobals.require} !== "undefined") {
```
Comment (utlime) [inline src/index.js:35]: Is it possible check on compiling?

Comment (markjm) [reply src/index.js:35]: I also looked at checking if the mainTemplate.require hook is called first, and register this hook only when that one has been called. I chose this route because (1) i dont know how that approach will interact with any other plugins touching these hooks and (2) the mainTemplate.require hook is slated to be removed in WP6 (per TODO comments in webpack source)

File: package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "webpack-retry-chunk-load-plugin",
-  "version": "2.0.2",
+  "version": "2.0.3",
```
Comment (mattlewis92) [inline package.json:3]: Can you revert this please? It will get bumped automatically when doing `npm version patch` (which also adds the git tag)

**Review by mattlewis92 — APPROVED** [review]
LGTM! Just need to revert the version bump and I think we can merge it

File: package.json (hunk 2 above)
Comment (markjm) [reply package.json]: done!

**Comment by mattlewis92** [comment]
Released as `2.0.3`, thank you!
