### PR TITLE
fix: restore chunks option in v2

### LINKED ISSUE #15: Does the chunks option work with webpack 5?
Looks like the chunks option is no longer used and all chunks get the retry logic regardless of the option being supplied.

https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/commit/cd6c7a59b4a6293982f1329295880df6be7ee1c7#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L92-L114

I was trying this out with a Webpack 4 project (using v1.0.2) and I noticed that regardless of which chunk is missing I always end up on the page specified in the lastResortScript. I was going through that code when I noticed that in the latest master chunks passed in the options is not used.

### PR DESCRIPTION
**Pull request by salzhrani**
Fixes #15

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -25,7 +25,12 @@ class RetryChunkLoadPlugin {
           : '"cache-bust=true"';
       mainTemplate.hooks.localVars.tap(
         { name: pluginName, stage: 1 },
-        (source) => {
+        (source, chunk) => {
+          const currentChunkName = chunk.name;
+          const addRetryCode =
+            this.options.chunks == null ||
```
Comment (mattlewis92) [inline src/index.js:31]: The linter is failing because of this, I think it's better to keep it as `!this.options.chunks` as it will be `undefined` and not `null` if the option isn't passed

**Review by mattlewis92 — CHANGES_REQUESTED** [review]
Thank you for the super quick turnaround on this! Just that one small issue and we should be g2g

**Review by mattlewis92 — APPROVED** [review]
LGTM, thank you!!
